CLASSIFY_AND_EXTRACT_PROMPT = """You are an expert startup analyst. Analyze the following input and extract structured information.

INPUT:
{user_input}

Respond ONLY with valid JSON in this exact format:
{{
  "input_type": "<one of: GitHub Repo, Website, Competitor, Product Hunt, Reddit, Hacker News, Social Post, Startup Idea, Conversation>",
  "product_name": "<name or 'Unknown'>",
  "product_category": "<category>",
  "core_problem": "<one sentence describing the problem being solved>",
  "target_audience": "<who this is for>",
  "keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"],
  "competitors": ["competitor1", "competitor2", "competitor3"]
}}

Be specific and concise. Keywords should be search-friendly terms for market research."""


VALIDATION_REPORT_PROMPT = """You are a world-class startup analyst with deep expertise in market validation, competitive intelligence, and product strategy.

## INPUT CONTEXT
Input Type: {input_type}
Product Name: {product_name}
Product Category: {product_category}
Core Problem: {core_problem}
Target Audience: {target_audience}
Keywords: {keywords}

## RESEARCH DATA
{research_data}

## TASK
Generate a comprehensive validation report in Markdown. Be direct, evidence-based, and brutally honest.

Use this exact structure:

# {product_name} — Validation Report

## 🧭 Product Understanding
**What is this product?**
[2-3 sentences]

**Who is it for?**
[1-2 sentences]

**What value does it provide?**
[1-2 sentences]

---

## 🔥 Problem Analysis
**What problem does it solve?**
[2-3 sentences]

**How painful is the problem? (1-10 scale with explanation)**
[1-2 sentences with score]

**Who experiences it most acutely?**
[1-2 sentences]

---

## 👥 Target Users
**Primary Users**
[bullet list]

**Secondary Users**
[bullet list]

**Ideal Customer Profile**
[3-4 sentences describing the ICP]

---

## 📊 Market Signals
**Evidence of Demand**
[bullet list of concrete signals from research]

**Pain Points Observed**
[bullet list]

**Community Discussions**
[bullet list with sources if available]

---

## ⚔️ Competitor Analysis
| Competitor | Positioning | Strengths | Weaknesses | Pricing |
|---|---|---|---|---|
[fill in table rows]

**Competitive Landscape Summary**
[2-3 sentences]

---

## 💰 Monetization Evidence
**Who is already making money in this space?**
[bullet list]

**Business Models Present**
[bullet list]

**Evidence of Paid Demand**
[2-3 sentences with concrete examples]

---

## 🚀 Startup Opportunities
**Potential Niches**
[bullet list]

**Underserved Segments**
[bullet list]

**Geographic / Industry Opportunities**
[bullet list]

---

## ⚠️ Risks
**Competition Risk:** [High/Medium/Low] — [explanation]
**Technical Complexity:** [High/Medium/Low] — [explanation]
**Market Saturation:** [High/Medium/Low] — [explanation]
**Distribution Challenge:** [High/Medium/Low] — [explanation]

---

## 🎯 GO / NO-GO Score

**Score: {score}/10**

**Decision: {decision}**

**Confidence Level: {confidence}**

**Explanation:**
[3-5 sentences justifying the score]

---

## 🛠️ 2-Week MVP Recommendation

{mvp_section}

---
*Generated by Founder Validation Copilot*"""


SCORE_PROMPT = """Based on the following startup analysis, provide a GO/NO-GO assessment.

Product: {product_name}
Category: {product_category}
Core Problem: {core_problem}
Target Audience: {target_audience}
Research Summary: {research_summary}

Respond ONLY with valid JSON:
{{
  "score": <integer 0-10>,
  "decision": "<GO | NO-GO | PIVOT>",
  "confidence": "<High | Medium | Low>",
  "score_explanation": "<2-3 sentences>",
  "build_mvp": <true | false>,
  "mvp_features": ["feature1", "feature2", "feature3"],
  "mvp_scope": "<2-3 sentences on what to build>",
  "mvp_launch_strategy": "<2-3 sentences on how to launch>"
}}"""


BRD_PROMPT = """You are a senior product manager. Generate a Business Requirements Document (BRD) based on this validation report.

## Validation Report Summary
Product: {product_name}
Category: {product_category}
Problem: {core_problem}
Target Audience: {target_audience}
Score: {score}/10
Decision: {decision}

## Full Report
{report_markdown}

Generate a complete BRD.md in Markdown with these sections:

# Business Requirements Document
## {product_name}

**Version:** 1.0
**Date:** {date}
**Status:** Draft

---

## 1. Executive Summary
[3-4 sentences]

## 2. Problem Statement
### 2.1 Current State
[describe the problem landscape]

### 2.2 Pain Points
[bullet list]

### 2.3 Impact
[quantify the problem if possible]

## 3. Target Users
### 3.1 Primary Users
[description + bullet list of characteristics]

### 3.2 Secondary Users
[description]

### 3.3 Ideal Customer Profile
[detailed ICP]

## 4. Market Analysis
### 4.1 Market Size Estimate
[TAM/SAM/SOM if possible]

### 4.2 Competitive Landscape
[summary of competitors]

### 4.3 Market Opportunity
[the gap this product fills]

## 5. Product Vision
### 5.1 Vision Statement
[one sentence]

### 5.2 Mission
[2-3 sentences]

### 5.3 Success Metrics
[bullet list of KPIs]

## 6. Features & Requirements
### 6.1 Core Features (Must Have)
[numbered list]

### 6.2 Important Features (Should Have)
[numbered list]

### 6.3 Nice to Have (Could Have)
[numbered list]

### 6.4 Out of Scope
[numbered list]

## 7. MVP Scope
### 7.1 MVP Definition
[what the 2-week MVP is]

### 7.2 MVP Features
[bullet list]

### 7.3 MVP Success Criteria
[bullet list]

## 8. Monetization Strategy
### 8.1 Business Model
[description]

### 8.2 Pricing Strategy
[description]

### 8.3 Revenue Projections
[conservative estimates]

## 9. Go-To-Market Strategy
### 9.1 Launch Strategy
[description]

### 9.2 Distribution Channels
[bullet list]

### 9.3 Early Adopter Strategy
[description]

## 10. Roadmap
### Phase 1: MVP (Weeks 1-2)
[bullet list]

### Phase 2: Validation (Weeks 3-6)
[bullet list]

### Phase 3: Growth (Months 2-3)
[bullet list]

## 11. Risks & Mitigations
| Risk | Likelihood | Impact | Mitigation |
|---|---|---|---|
[fill in rows]

## 12. Appendix
### A. Research Sources
[from validation report]

### B. Competitor Details
[from validation report]

---
*Generated by Founder Validation Copilot*"""
